### PR TITLE
Remove update event

### PR DESCRIPTION
**Pull request by jackchalat**

### CODE REVIEW

**Comment by aokiken** [comment]
@jackchalat hi!
Did you have any problems?

**Comment by jackchalat** [comment]
@aokiken Hi. Sorry I made this by mistake. I forked my own branch and made the change instead. I apologize for the trouble.

**Comment by aokiken** [comment]
Don’t worry, but I'm interesting why you made the change.

Can you tell me the reason?

**Comment by jackchalat** [comment]
@aokiken  I am using this library to remove whitespace for a Thai language Buddhist text reader. The read has text-to-speech with line highlighting.

For some reason, Vue added whitepsace to Thai language characters. So your library helped fixed that. But the library also removes whitespace on component update event. This mistakenly remove whitespace when the read highlight is applied to the text.

Here is the problem with `componentUpdated`. I circled the problem in red. The removal of this whitespace caused the highlighter to become not synced with the text. The highlight library I am using is mark.js . 

whitespace-remove-on-update

So I removed `componentUpdated`. And it is now working correctly.

whitespace-remove-on-update-good

I think it would be good to have an option to disable `componentUpdated` event as other users might find this issue in the future. 

Thank you for making this library. It helps me a lot.

**Pull request closed without merging**
